- .github/workflows/docker-image.yml
- Dockerfile
- app/mock-registry/src/Storage/Queries/Subscriber.hs
- app/mock-registry/src/Storage/Tabular/Subscriber.hs
- stack.yaml
- stack.yaml.lock
> added Dockerfile for beckn-gateway

- .envrc
- .gitignore
- Jenkinsfile
- cabal.project
- flake.lock
- flake.nix
https://github.com/nammayatri/nammayatri/issues/9
The `nixify` branch will be used to merge the various Nix PRs on to. 
Once the team is ready to use Nix, we will merge `nixify` onto `main`.
> Nixification

- .gitignore
- app/gateway/beckn-gateway.cabal
- app/mock-registry/mock-registry.cabal
And don't ignore them in Git.
The cabal files are generated with `hpack` from nix shell.
> Add .cabal files

- app/gateway/src/Product/Search.hs
- flake.lock
- stack.yaml
- stack.yaml.lock
prometheus url cleaning
PR link
https://github.com/nammayatri/shared-kernel/pull/85
> prometheus url cleaning

- Jenkinsfile
> jenkins: cachix push on `main` only

- Jenkinsfile
> jenkins: Build on nixos

- app/gateway/src/App/Types.hs
- dhall-configs/dev/beckn-gateway.dhall
- flake.lock
> Added support for redis cluster

- app/gateway/src/App/Types.hs
- dhall-configs/dev/beckn-gateway.dhall
added cluster redis cut off support
> Added redis cluster cutoff support

- Jenkinsfile
The CI will now build for both arm and intel Mac, and push to cachix.
Note: docker image will be pushed only on Linux (and in `main` branch).
> jenkins: Build on macOS

- Jenkinsfile
> jenkins: Use `none` agent globally

- app/gateway/src/App/Server.hs
- flake.lock
https://github.com/nammayatri/nammayatri/issues/769
To do staggered deployments, we need to compare 4xx/ 5xx b/w the current and previous version across routes.
To monitor through Prom metrics, we need to add the version label in the metric: http_request_duration_seconds_count.
> backend/feat: #769 version label for middleware metrics

- flake.lock
- flake.nix
> backend/nix: Share all inputs of common

- .gitignore
> .gitignore: Ignore cache dirs

- flake.lock
> backend: gateway backward compatible

- app/gateway/beckn-gateway.cabal
- app/gateway/package.yaml
- app/gateway/src/App.hs
- app/gateway/src/Product/Search.hs
- app/gateway/src/Types/Beckn/API/Callback.hs
- app/gateway/src/Types/Beckn/Context.hs
- flake.lock
> backend/feat: add KV related changes

- app/gateway/src/Product/Search.hs
- app/mock-registry/src/Flow/Lookup.hs
- flake.lock
> backend:made withFlowHandleApi beckn and mock compatible

- app/gateway/src/Product/Search.hs
- flake.lock
> routing the bap bpp calls internally

- README.md
(Mainly to test Jenkins behaviour)
> readme: Link to ny readme

- Jenkinsfile
> Update Jenkinsfile, removed intel Mac build from CI/CD.

- app/mock-registry/src/Storage/Queries/Subscriber.hs
- app/mock-registry/src/Storage/Tabular/Subscriber.hs
- dev/migrations/001-alter-city-type.sql
- flake.lock
> multiple city support added

- app/gateway/beckn-gateway.cabal
- app/gateway/package.yaml
- app/gateway/src/App/Types.hs
- app/gateway/src/Product/Search.hs
- dhall-configs/dev/beckn-gateway.dhall
- dhall-configs/dev/common.dhall
- dhall-configs/generic/common.dhall
- flake.lock
> routing bap and bpp calls fix

- app/gateway/beckn-gateway.cabal
- app/gateway/package.yaml
- app/gateway/src/App/Types.hs
- flake.lock
> backend/fix: using container package for hashmaps

- app/gateway/src/Product/ProviderRegistry.hs
- app/gateway/src/Types/Beckn/Context.hs
Changes for this [PR](https://github.com/nammayatri/nammayatri/pull/5181)
> backend/feat/beckn-spec-v2: changes related to context for beckn-spec-v2

- app/gateway/src/Product/ProviderRegistry.hs
- app/gateway/src/Types/Beckn/Context.hs
> backend/fix: make gateway backward compatible for beckn spec

- app/gateway/src/Product/Search.hs
- app/gateway/src/Types/API/Search.hs
- flake.lock
Fix registry lookup in shared kernel
Include domain and type in lookup API
> backend/feat: send subscriber type in registry lookup api

- app/gateway/src/App/Types.hs
- app/mock-registry/src/App/Types.hs
- flake.lock
> backend: adding env for ART

- flake.lock
> backend/enhancement: Shared kernel version update

- flake.lock
> backend/fix: Cities

- .github/workflows/nix.yml
Same as https://github.com/nammayatri/nammayatri/pull/8494
> ci: Build flake outputs on self-hosted runner

- app/mock-registry/src/Storage/Queries/Subscriber.hs
> fix: remove city check for subscribers with city as '*'
